import argparse
import ast


def _bool_arg(name, default=False, help_text=""):
    parser.add_argument(name, type=ast.literal_eval, default=default, help=help_text)


parser = argparse.ArgumentParser(description="Evaluation for continual video anomaly detection")

# runtime
parser.add_argument("--device", type=str, default="0", help="GPU id, e.g. 0 or cuda:0")
parser.add_argument("--seed", type=int, default=1, help="random seed")

# dataset
parser.add_argument("--dataset_name", type=str, default="ucfcrime", help="ucfcrime or shanghaitech")
parser.add_argument("--dataset_path", type=str, default="./dataset", help="dataset root")
parser.add_argument("--data_mode", type=str, default="single_video", choices=["single_video", "concat"])
parser.add_argument("--feature_path", type=str, default="", help="feature directory for single_video mode")
parser.add_argument("--train_split_file", type=str, default="train_split_10crop.txt")
parser.add_argument("--test_split_file", type=str, default="test_split_10crop.txt")
parser.add_argument("--feature_suffix", type=str, default=".npy")
parser.add_argument("--clip_len", type=int, default=10)
parser.add_argument("--test_clip_stride", type=int, default=1)
parser.add_argument("--ucf_train_npy", type=str, default="", help="concat train npy used only to infer feature dim")
parser.add_argument("--ucf_test_npy", type=str, default="", help="concat/global test feature npy")
parser.add_argument("--eval_gt_npy", type=str, default="./gt-ucf-RTFM.npy")
parser.add_argument("--concat_meta_json", type=str, default="")
parser.add_argument("--ucf_gt_pickle", type=str, default="")
parser.add_argument("--sh_gt_pickle", type=str, default="")
parser.add_argument("--video_label_pickle", type=str, default="")
parser.add_argument("--eval_log_prefix", type=str, default="")

# concat evaluation
_bool_arg("--concat_test_use_cross", default=False)
parser.add_argument("--concat_test_score_mode", type=str, default="first", choices=["first", "mean", "max", "last"])
_bool_arg("--use_eval_postproc", default=False)
parser.add_argument("--test_smooth_kernel", type=int, default=1)
parser.add_argument("--test_persist_alpha", type=float, default=0.0)
parser.add_argument("--test_persist_blend", type=float, default=0.0)
parser.add_argument("--test_persist_mode", type=str, default="forward")
parser.add_argument("--test_second_smooth_kernel", type=int, default=1)
parser.add_argument("--test_score_gamma", type=float, default=1.0)
parser.add_argument("--test_video_norm_mix", type=float, default=0.0)
parser.add_argument("--test_video_norm_temp", type=float, default=1.0)
parser.add_argument("--test_video_qnorm_mix", type=float, default=0.0)
parser.add_argument("--test_video_qnorm_low", type=float, default=5.0)
parser.add_argument("--test_video_qnorm_high", type=float, default=95.0)
parser.add_argument("--test_video_contrast_mix", type=float, default=0.0)
parser.add_argument("--test_video_contrast_low", type=float, default=50.0)
parser.add_argument("--test_video_contrast_high", type=float, default=95.0)
parser.add_argument("--test_video_contrast_temp", type=float, default=0.08)
parser.add_argument("--test_video_contrast_floor", type=float, default=0.45)
parser.add_argument("--test_video_baseline_mix", type=float, default=0.0)
parser.add_argument("--test_video_baseline_q", type=float, default=55.0)
parser.add_argument("--test_video_baseline_strength", type=float, default=0.45)
_bool_arg("--test_video_baseline_rescale", default=True)
parser.add_argument("--test_peak_boost", type=float, default=0.0)
parser.add_argument("--test_peak_percentile", type=float, default=90.0)
_bool_arg("--save_pr_curve", default=False)

# model shape
parser.add_argument("--max_seqlen", type=int, default=800)
parser.add_argument("--feature_size", type=int, default=512)
parser.add_argument("--proj_feature_size", type=int, default=0)
parser.add_argument("--Vitblock_num", type=int, default=2)
parser.add_argument("--cross_clip", type=int, default=1)
parser.add_argument("--scorer_dropout", type=float, default=0.7)
parser.add_argument("--scorer_hidden1", type=int, default=0)
parser.add_argument("--scorer_hidden2", type=int, default=128)
parser.add_argument("--input_norm", type=str, default="none", choices=["none", "layernorm", "l2"])
parser.add_argument("--beta", type=float, default=0.05)
parser.add_argument("--delta", type=float, default=0.0)
parser.add_argument("--score_rec_consistency_weight", type=float, default=0.0)

# optional inference blends
_bool_arg("--hard_route_infer", default=False)
_bool_arg("--infer_with_teacher", default=False)
parser.add_argument("--infer_teacher_alpha", type=float, default=0.7)
_bool_arg("--infer_with_anchor", default=False)
parser.add_argument("--infer_anchor_alpha", type=float, default=0.8)
_bool_arg("--infer_with_recon", default=False)
parser.add_argument("--infer_recon_alpha", type=float, default=0.8)
_bool_arg("--infer_with_memory_novelty", default=False)
parser.add_argument("--infer_memory_alpha", type=float, default=0.8)
_bool_arg("--infer_memory_frozen_only", default=False)
_bool_arg("--full_evidence_enable", default=False)
parser.add_argument("--full_evidence_loss_weight", type=float, default=0.0)
_bool_arg("--full_evidence_infer", default=False)
parser.add_argument("--full_evidence_alpha", type=float, default=0.65)
parser.add_argument("--full_evidence_rec_weight", type=float, default=1.0)
parser.add_argument("--full_evidence_temp_weight", type=float, default=0.35)
parser.add_argument("--full_evidence_center_weight", type=float, default=0.25)
parser.add_argument("--full_evidence_power", type=float, default=1.0)

# architecture switches saved checkpoints may depend on
_bool_arg("--use_qavclab", default=False)
parser.add_argument("--short_clip", type=int, default=2)
parser.add_argument("--long_clip", type=int, default=4)
parser.add_argument("--retrieval_topk", type=int, default=16)
parser.add_argument("--retrieval_samples", type=int, default=32)
parser.add_argument("--bank_decay", type=float, default=0.9)
parser.add_argument("--bank_age_weight", type=float, default=0.05)
parser.add_argument("--difficulty_weight", type=float, default=0.6)
parser.add_argument("--uncertainty_weight", type=float, default=0.2)
parser.add_argument("--consistency_weight", type=float, default=0.2)
parser.add_argument("--teacher_momentum", type=float, default=0.995)
parser.add_argument("--teacher_threshold", type=float, default=0.5)
parser.add_argument("--min_pseudo_pos", type=float, default=0.03)
parser.add_argument("--max_pseudo_pos", type=float, default=1.0)
parser.add_argument("--max_pseudo_pos_start", type=float, default=-1.0)
parser.add_argument("--max_pseudo_pos_end", type=float, default=-1.0)
parser.add_argument("--max_pseudo_pos_anneal_iters", type=int, default=0)
parser.add_argument("--pseudo_loss_mode", type=str, default="bce", choices=["bce", "balanced_bce"])
parser.add_argument("--pseudo_pos_weight_max", type=float, default=6.0)
parser.add_argument("--pseudo_rank_weight", type=float, default=0.0)
parser.add_argument("--pseudo_rank_margin", type=float, default=0.10)
parser.add_argument("--pseudo_rank_max_samples", type=int, default=128)
parser.add_argument("--pseudo_rank_neg_ratio", type=float, default=1.0)
parser.add_argument("--rec_rank_weight", type=float, default=0.0)
parser.add_argument("--rec_rank_margin", type=float, default=0.08)
parser.add_argument("--rec_rank_top_ratio", type=float, default=0.10)
parser.add_argument("--rec_rank_bottom_ratio", type=float, default=0.25)
parser.add_argument("--rec_rank_max_samples", type=int, default=128)
parser.add_argument("--easy_neg_weight", type=float, default=0.0)
parser.add_argument("--easy_neg_ratio", type=float, default=0.35)
parser.add_argument("--easy_neg_margin", type=float, default=0.18)
parser.add_argument("--easy_neg_max_samples", type=int, default=192)
parser.add_argument("--easy_neg_focus_ratio", type=float, default=1.0)
parser.add_argument("--score_sparse_weight", type=float, default=0.0)
parser.add_argument("--score_sparse_target", type=float, default=0.22)
parser.add_argument("--score_sparse_flat_weight", type=float, default=0.0)
parser.add_argument("--score_sparse_flat_margin", type=float, default=0.18)
parser.add_argument("--score_sparse_top_ratio", type=float, default=0.25)
parser.add_argument("--score_sparse_rec_aware", type=float, default=0.0)
parser.add_argument("--score_sparse_min_weight", type=float, default=0.25)
_bool_arg("--enforce_min_pseudo_pos", default=False)
parser.add_argument("--lab_start_iter", type=int, default=100)
parser.add_argument("--route_start_iter", type=int, default=100)
_bool_arg("--enable_teacher_gate", default=False)
parser.add_argument("--teacher_gate_start_iter", type=int, default=200)
parser.add_argument("--route_batch_cap", type=int, default=256)
_bool_arg("--freeze_c2fpl", default=False)

# incremental memory settings
_bool_arg("--inc_enable", default=False)
parser.add_argument("--inc_scene_id", type=int, default=0)
parser.add_argument("--inc_memory_max", type=int, default=256)
parser.add_argument("--inc_memory_init", type=int, default=16)
parser.add_argument("--inc_match_temp", type=float, default=0.07)
parser.add_argument("--inc_match_threshold", type=float, default=0.55)
parser.add_argument("--inc_match_sim_threshold", type=float, default=0.55)
parser.add_argument("--inc_expand_warmup_iters", type=int, default=50)
parser.add_argument("--inc_proto_momentum", type=float, default=0.95)
parser.add_argument("--inc_mem_easy_ratio", type=float, default=1.0)
parser.add_argument("--inc_mem_score_quantile", type=float, default=0.70)
parser.add_argument("--inc_mem_score_weight", type=float, default=1.2)
parser.add_argument("--inc_replay_ratio", type=float, default=0.25)
parser.add_argument("--inc_replay_max_samples", type=int, default=128)
parser.add_argument("--inc_replay_scene_quota", type=int, default=12)
parser.add_argument("--inc_replay_topk", type=int, default=4)
parser.add_argument("--inc_replay_alpha", type=float, default=0.7)
parser.add_argument("--inc_replay_noise", type=float, default=0.02)
parser.add_argument("--inc_replay_min_sim", type=float, default=-1.0)
parser.add_argument("--inc_replay_hard_ratio", type=float, default=0.5)
parser.add_argument("--inc_replay_weight", type=float, default=0.3)
parser.add_argument("--inc_replay_warmup_iters", type=int, default=80)
parser.add_argument("--inc_replay_score_weight", type=float, default=1.0)
parser.add_argument("--inc_replay_loss_mode", type=str, default="full", choices=["full", "rec", "anchor_only", "none"])
_bool_arg("--inc_replay_putback_memory", default=True)
parser.add_argument("--inc_expected_scenes", type=int, default=13)
parser.add_argument("--inc_scene_proto_cap", type=int, default=0)
parser.add_argument("--inc_scene_min_slots", type=int, default=0)
parser.add_argument("--inc_overflow_policy", type=str, default="far", choices=["far", "similar", "redundant"])
_bool_arg("--inc_overflow_expand", default=False)
parser.add_argument("--inc_anchor_replay_weight", type=float, default=0.0)
